### PR TITLE
use USRPHardwareDriver in Yggdrasil/Pkg as libuhd provider

### PR DESCRIPTION
**Pull request by sjkelly**
Hi @RGerzaguet ! We have packaged libuhd in Yggdrasil, which should simplify some of the deployment here and add support for more platforms and architectures to this package. This uses `USRPHardwareDriver_jll` to provide libuhd. Unfortunately I do not have a USRP, so please be sure to test and let me know if there are issues here.

### CODE REVIEW

**Comment by RGerzaguet** [comment]
Wonderfull @sjkelly I really appreciate your help on this topic.
 I am really willing to switch to binary builders, I have still some opening questions/remarks, and maybe you can give me some insights

 - UHD has some trouble with (retro) compatibility between versions. On the different devices we have in our lab we have chosen to use UHD~4.0 (the version shipped in the manual artifact). We have some e310 and we must have the same version on the ARM side and on the PC side. With the provided code, the version 4.1 gives runtime errors (not linked to your code though, but only due to version mismatch). Would it be possible to generates builders for 4.0 ? 
 - An alternative would be to be able to generate builders for different version of UHD (4.0 and 4.1 at the next ones ?), don't really know how we can leverage Yggrasil for that (different repo ? Multiple tarballs in same repo ?). 
 - In the last version of UHD and following #4 I have added some code to always promote local install instead of artifact. Ideally, this should be to the choice of the user. Even more idealistic, the user may choose which version of UHD (i.e which jll package). But how to do this ? An ENV variable ? A specific configuration file ? Something else ?


 Anyway many thanks for providing the tarballs :)
 @+R

**Comment by sjkelly** [comment]
Good info, thanks! We should be able to generate 4.0 and 4.1 binaries. I'll have to do some investigating and ask around about the way to do this, but this shouldn't be an issue. FWIW these binaries are ARM, X86, Linux/Mac/BSD and they should all be compatible. Do you think it would be better to upgrade to 4.1?

A good way to control binary providers is through https://github.com/JuliaPackaging/Preferences.jl

**Comment by sjkelly** [comment]
This may be better for overriding artifacts: https://pkgdocs.julialang.org/v1/artifacts/#Overriding-artifact-locations

**Comment by RGerzaguet** [comment]
Hello @sjkelly 
Great news, the version you have provided works perfectly on x86 Linux distributions. I add some trouble related to the switch of UHD41 to our e3xx devices but it is now solved (and this is independent from your proposal)
I have slightly updated the code you have worked on to add  
- a Preferences.jl system to be able to switch from all package and "local" installation. By setting `UHDBindings.set_provider("local")` the used lib will now be the one on your system (better than what we have done in https://github.com/JuliaTelecom/UHDBindings.jl/pull/4). If  we have several jll packages in the future (for several UHD versions) it will allow us to easy switch from all package versions.
- I add some issue with deadlocks with our e3xx SDR due to streamer issue. This is something that comes to streamer restart policy and I have made an update of `recv!` code to solve that.

Last step is to be sure that the test works on Mac, I will try to do this next week.  Probably merge this at the same time we switch to libiio on AdalmPluto side for convergence.

Many many thanks for initiating this, this is a really better system I believe

**Pull request merged**
